### PR TITLE
Add Java-Spock-Gradle version

### PR DESCRIPTION
**Pull request by kiview**
I've added a version which setups Gradle as the Java build tool and uses Spock as the Testing-Framework, to have a  more **modern** Java project which uses a reald build system instead of a tight IDE integration (although IDE integration with IDEs support Gradle still works out of the box).

### CODE REVIEW

**Comment by emilybache** [comment]
Hi,
Is it possible to merge this with the existing Java version? The only difference seems to be the build system and the test framework that's being used. Does it need to be in a separate folder? Couldn't the spock build stuff live alongside the ide integration? We could have two starting files for unit testing, and let people choose which framework they prefer.

I'd like to avoid maintaining too many copies of the same code if at all possible.

Emily

**Comment by kiview** [comment]
I think this is possible without problems, I simply was not sure, if this would make the Java package to bloated/confusing. I'll merge the code accordingly.

**Comment by emilybache** [comment]
Thankyou!

**Comment by kiview** [comment]
Sorry for not merging the project with the original Java project, did not have the time for it :(
Should I still look into merging this?

**Pull request merged**
