### PR TITLE
add ci - start with jq

### PR DESCRIPTION
**Pull request by nitsanavni**
### Why?

With all these translations and code, it's nice to know it actually works, and it'll be nice to know when it stops working.

### About the CI workflow

- it is only triggered on PRs to main
- it is only triggered when changing anything in the `jq` subfolder
- it tests for two things:
  1. the unit test is failing
  2. verifies the texttest fixture result

### See it in Action (get it?)

- [An intentional failure](https://github.com/nitsanavni/GildedRose-Refactoring-Kata/actions/runs/4114858452/jobs/7102783987)
- [A successful run](https://github.com/nitsanavni/GildedRose-Refactoring-Kata/actions/runs/4114911448/jobs/7102908994)

Also, thanks ChatGPT for getting me started with an initial draft.

### CODE REVIEW

**Comment by emilybache** [comment]
Thanks for suggesting this. I'm intrigued. 
Instead of providing the 10 days file to compare against, is it possible to run the 30 days texttest? Either using the actual texttest executable or by just comparing against the stdout file? 

https://github.com/emilybache/GildedRose-Refactoring-Kata/blob/main/texttests/ThirtyDays/stdout.gr

I like that you also check the unit test fails. 

How easy would it be to add similar github actions for the other language versions?

**Comment by nitsanavni** [comment]
> How easy would it be to add similar github actions for the other language versions?

I guess some easier than others :)

> Instead of providing the 10 days file to compare against, is it possible to run the 30 days texttest? Either using the actual texttest executable or by just comparing against the stdout file?

Oh I did not notice this file, of course we could compare to that one. And I wonder if the jq impl will result in an exact match 🤔

About the texttest executable - I can give it a try, although I have to say I like the simplicity of:
```shell
<30-day-fixture> | diff - ../texttests/ThirtyDays/stdout.gr
```

**Comment by nitsanavni** [comment]
indeed I had some copy-paste bugs :)

but comparing to the 30-days result now works.

you can see the workflow run [here](https://github.com/nitsanavni/GildedRose-Refactoring-Kata/actions/runs/4116385224/jobs/7106369489)

**Comment by codecop** [comment]
I have many integrations working for the Parrot, see https://github.com/codecop/Parrot-Refactoring-Kata/tree/github-build just using unit tests, so would need changes though.

**Comment by nitsanavni** [comment]
@codecop very cool! Should be very useful.

**Comment by emilybache** [comment]
Ok let's give this a go. Thankyou!

**Pull request merged**
