### PR TITLE
Restructure .NET Core solution to follow best practice

### PR DESCRIPTION
**Pull request by un1r8okq**
As I started to refactor this Kata, the first thing I did was split the tests out into their own C# project. I think most people will do this as the first step of refactoring, however, it doesn't add much value as a learning experience.

This change is more nuanced than [my PR to update the .NET version](https://github.com/emilybache/GildedRose-Refactoring-Kata/pull/251), so hear me out.

**My Reasoning**
- [Microsoft recommends a separate project for tests in its tutorials](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2019#create-a-unit-test-project).
- Most other languages in this repository follow this pattern (26/46).
- This is the only way I've seen it done in my industry experience.

>Okay, but what about [the .NET Framework project](https://github.com/emilybache/GildedRose-Refactoring-Kata/tree/main/csharp)? It doesn't have a separate test project.

Sure. I see three options. I'll list them in my preferred order:
1. Delete the .NET Framework project in a future PR (my preferred option). If this Kata is about refactoring in different languages, the .NET Framework project doesn't add any value. Both .NET Core and .NET Framework are written in C#. The only difference is the underlying libraries and runtime. Also, [Microsoft have said that the future of .NET is .NET Core](https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/). .NET Framework won't be receiving any updates in the future. I think that this Kata should contain languages in their latest stable form, not previous iterations of them.
2. Update the .NET Framework to have a separate test project in a separate PR. I'm also happy to do this.
3. Leave this solution containing both business code and test code. People who refactor it will likely spend 15 minutes splitting it out into two projects to follow best practice. They probably won't learn much from doing it.

@emilybache I'd love to hear your thoughts on this 🙂

### CODE REVIEW

**Comment by emilybache** [comment]
Hi,
- You've misspelled Gilded rose as GuildedRose in a few places
- I'm otherwise happy to accept a pull request that puts the tests in their own project.
- I didn't understand the question about .net core vs .net framework. If it's already in .net core and that is the future then isn't it already ok as it is?

Thanks for helping me with a language I know less about!

**Comment by un1r8okq** [comment]
Hi Emily! Nice spotting of the spelling mistake. I've fixed this 🙂

**Comment by un1r8okq** [comment]
>I didn't understand the question about .net core vs .net framework. If it's already in .net core and that is the future then isn't it already ok as it is?

Apologies for the confusing topic that wasn't very relevant for this specific PR. My point around .NET Framework can be summed up as this:

- [.NET Framework and .NET Core are both libraries and runtimes that the C# language runs on](https://stackoverflow.com/questions/2724864/what-is-the-difference-between-c-sharp-and-net).
- [Microsoft has deprecated .NET Framework in favor of .NET Core](https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/). .NET Framework will no longer receive updates, and the next version of .NET Core will be called ".NET".
- Since this kata is about providing a refactoring challenge in different languages, there is no benefit for keeping the .NET Framework project around.
- Therefore, in a future change, we should probably remove the .NET Framework project and just have a "csharp" project that runs on the latest version of .NET - .NET Core.

**Comment by un1r8okq** [comment]
@emilybache bump in case it fell off your radar 👀

**Comment by emilybache** [comment]
Thankyou! Sorry for the delay, I was on vacation.

**Pull request merged**
