### PR TITLE
Add Zig implementation

### PR DESCRIPTION
**Pull request by eauc**
- [x] I acknowledge that this PR is not a solution to the Gilded Rose Kata, but an improvement to the template.

## Please provide your PR description below this line

A [Zig](https://ziglang.org/) implementation of the kata.

I'm still a noob in Zig, this is my first ever project, but I think it runs correctly.
TestTexts are implemented and seem to work.

I'll probably continue to play with it so I might push some improvements later.

PS: thanks for maintaining this project, you're awesome :pray:

### CODE REVIEW

**Comment by codecop** [comment]
Awesome. An empty unit Test with failing assert foo != Fixme would be nice to get startet

**Comment by eauc** [comment]
> Awesome. An empty unit Test with failing assert foo != Fixme would be nice to get startet. Also I saw a reference to "c" in the readme

there is one ! https://github.com/emilybache/GildedRose-Refactoring-Kata/pull/546/files#diff-3876cc2043d61c8e49cf45fe09a4c3fb72fc784a1e663436e47d2a03de0aa325R74

in Zig test are traditionnally in the same file as their unit (or so it seems)

they just get compiled away when you build the production artifact

**Comment by codecop** [comment]
OK. The one thing I am missing now is a .gitignore file for zig. Sorry I did not think of it before.

**Comment by eauc** [comment]
> OK. The one thing I am missing now is a .gitignore file for zig. Sorry I did not think of it before.

no problem, here you go.

**Comment by codecop** [comment]
Thank you

**Comment by emilybache** [comment]
Thank you both!

**Pull request merged**
