### PR TITLE
Add Delphi port

### PR DESCRIPTION
**Pull request by rhatherall**
Adds port using Delphi 10.3 with [DUnitX](https://github.com/VSoftTechnologies/DUnitX).

### CODE REVIEW

**Comment by emilybache** [comment]
Thanks for this! You've included two binary files both '.res'. They appear to be test result files? Are they built from the unit test source code you've added? Can you tell me why these need to be included in the repo starting position?

**Comment by rhatherall** [comment]
No probs, thank you :)

Delphi automatically creates Windows resource files for each project. They contain information regarding things like platform support, icons, build information such as versions and build numbers. The files included here are vanilla files that will be recreated when the projects are built for the first time. I am happy to remove them and add to the `.gitignore`, if you prefer, as it will have no real impact on the usability of the project.

**Comment by emilybache** [comment]
I think it would be good to not include files that the user can easily re-create for themselves. This repo is quite large already! If it's not too much trouble could you fix that?

**Comment by rhatherall** [comment]
No problems. Done.

**Comment by emilybache** [comment]
Thankyou!

**Pull request merged**
