### PR TITLE
Csharp approval fixes

### PR DESCRIPTION
**Pull request by claresudbery**
Get approval tests working out of the box for C# code:
Update texttest config and add "approved" text file.

### CODE REVIEW

**Comment by emilybache** [comment]
I'm very grateful for the update to the texttest config. I'm less sure if I want the approved file. I hadn't included it before because I wanted people to run the test for themselves and understand enough about approval testing to realize they had to approve the file and what that meant. It's similar to how I give a unit test that is failing - I want people to understand why it fails and fix it to prove they understood what a unit test is and why it failing matters. Can you tell me why you want to include the approved file?

**Comment by claresudbery** [comment]
> I'm very grateful for the update to the texttest config. I'm less sure if I want the approved file. I hadn't included it before because I wanted people to run the test for themselves and understand enough about approval testing to realize they had to approve the file and what that meant. It's similar to how I give a unit test that is failing - I want people to understand why it fails and fix it to prove they understood what a unit test is and why it failing matters. Can you tell me why you want to include the approved file?

Ah ok, yes, it's because often when people are joining an online session they have to think about multiple things at once in order to catch up and get up and running, so the way I see it, the more I can remove friction the better. But I also see your point of view so I don't mind if that element is removed!

**Comment by claresudbery** [comment]
I've now done some work getting approval tests working "out of the box" for csharpcore as well as csharp. I've only just seen your previous response though - would you like me to remove the approved.txt files from each folder?

**Comment by emilybache** [comment]
Thankyou!

**Pull request merged**
