### PR TITLE
Added elixir build folder to ignored files

### PR DESCRIPTION
**Pull request by danielemegna**
Are you interested to include also the elixir __build_ folder to the git ignored path (as already done for the perl6 .precomp folder)?

### CODE REVIEW

**Comment by emilybache** [comment]
Hi, I think you didn't mean to include your second commit in this pull request? I'd accept the change to .gitignore but not the change to the elixir tests :-)

Emily

**Comment by danielemegna** [comment]
Hi Emily, yes of course! I'm sorry..

I opened the pull request when my master branch had only the first commit.
I should have fixed the pull request to the specific revision... ! 🙏 

Can you exclude the second commit from this pull request or you prefer to close this and open another (right) pull request?

Daniele

**Comment by emilybache** [comment]
It's easier for me if we close this one and you send another, I think. Thanks!

**Comment by danielemegna** [comment]
Here we are: https://github.com/emilybache/GildedRose-Refactoring-Kata/pull/68 :)

**Pull request closed without merging**
