### PR TITLE
PL/pg SQL: improve README (add requirements) / Add unit test framework (pgTAP)

### PR DESCRIPTION
**Pull request by GradedJestRisk**
This PR includes 2 commits, one for each feature, and can be split if appropriate.
The transaction validation (COMMIT) in update_quality.sql has been removed to enable tests to be deterministic.

### CODE REVIEW

**Comment by fpellet** [comment]
😃 Same idea
In parallel, I also made a postgres version (#137 ). I just saw that you proposed one.
My version already contains the setup.
Does it suit you?

**Comment by fpellet** [comment]
I moved my code in `plpgsql/pgunit`  
Can you move your code in `plpgsql/pgtap`  ?

There is an error on line 71 of `code/update_quality.sql`. Several product can have same name.

**Comment by GradedJestRisk** [comment]
PR updated to make way to pgUnit [PR 137](https://github.com/emilybache/GildedRose-Refactoring-Kata/pull/137)

**Comment by emilybache** [comment]
Hello, thankyou so much for your pull request. I see you are also contributing to the other pull request for a postgres sql version of this kata. Would you like me to accept both pull requests, or can you come up with one request between you?

**Comment by emilybache** [comment]
Thankyou!

**Pull request merged**
