### PR TITLE
Gilded Rose in Matlab 

### PR DESCRIPTION
**Pull request by Intrunatu**
# READ ME BEFORE SUBMITTING A PR

Please do not submit a PR with your solution to the Gilded Rose Kata. This repo is intended to be used as a starting point for the kata.

- [x] I acknowledge that this PR is not a solution to the Gilded Rose Kata, but an improvement to the template.

## Please provide your PR description below this line

Hello,

I have translated the code to Mathworks Matlab language from the Python implementation.

There are two test suites. One is complete to ensure the initial update_quality is correct and the other is the starting point that should be given to the users. If it is ok for you, I push a new commit without the complete test suite.

The TextTest function can be called with the number of days it should run as an argument. If omitted, it will run for two days.

Thanks for your work !

### CODE REVIEW

**Comment by Intrunatu** [comment]
This PR could close issue #213

**Comment by emilybache** [comment]
This looks great! Thankyou for the translation. I would just prefer if it didn't include complete unit tests

**Comment by Intrunatu** [comment]
Indeed, it was in case you wanted to test the initial implementation of `update_quality`.
I have amended and force pushed the commit so the test do not appear in the history.

**Comment by emilybache** [comment]
Brilliant, thankyou so much!

**Pull request merged**
