### PR TITLE
Create Kumari_Aastha_pyspark

### PR DESCRIPTION
**Pull request by aasthakittu**

### CODE REVIEW

**Comment by emilybache** [comment]
Hi, this code you've sent doesn't appear to be a translation of the starting position of this exercise. I'm not familiar with the programming language it uses so a translation would perhaps be interesting to have. Could you modify it to more closely match the other language versions?

Regards,
Emily

**Comment by aasthakittu** [comment]
Hi Emily,

Sorry for the confusion. I will translate it to pyhton 3 and send it to you
by Wednesday. Hope this is still works for you.

Regards,
Aastha

**Comment by aasthakittu** [comment]
Hi Emily,
I started assignment here https://github.com/emilybache/GildedRose-Refactoring-Kata (python) and looked at it to modify the same but the code looks complete and need no modification according to me . Please let me know if there is further action item for me. Hope to hearing you soon.
Thanks

**Comment by emilybache** [comment]
Thankyou but I think everything is fine

**Pull request closed without merging**
